vcpkg_from_git(
    OUT_SOURCE_PATH SOURCE_PATH
    URL https://github.com/google/draco.git
    REF 3abbc66fdf5597b1560c44ce7840aac76900b3f7
)

vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
        -DDRACO_WASM=ON
        -DDRACO_TRANSCODER_SUPPORTED=ON
        -DDRACO_BUILD_EXECUTABLES=OFF
)

vcpkg_cmake_install()
vcpkg_copy_pdbs()

# Clean up redundant include folders often generated by Draco
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")

# Standard License installation
file(INSTALL "${SOURCE_PATH}/LICENSE" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)